testing-library/testing-playground

src/components/App.js
src/components/ElementInfo.js
src/components/HtmlPreview.js
src/components/QueryAdvise.js
src/lib/index.js
src/lib/queryAdvise.js
src/styles/app.pcss

If a picture is worth a thousand words. Imagine what a gif is:

feat: add hover and click events to html preview area

---

.babelrc
package-lock.json
package.json
src/__mocks__/fileMock.js
src/components/App.test.js
tests/setupTests.js
tests/utils/render.js

I think that I have added what we need for testing.
In `setupTests.js` I have assigned to window object the export from testing library.

feat: add test setup based on jest and testing-library

---

.all-contributorsrc
README.md

To quote the all-contributors page:
> The basic idea is this:
> 
> Use the project README to recognize the contributions of members of the project community.
> 
> People are giving themselves and their free time to contribute to open source projects in so many ways, so we believe everyone should be praised for their contributions (code or not).
As a reminder, contributors can be added in two ways:
**command line**
```
npx all-contributors-cli add <username> <contributions>
```
**bot**
```
@all-contributors please add <username> for <contributions>
```
Contributions are comma-separated, and the types can be found here:
https://allcontributors.org/docs/en/emoji-key
---
resolves: #6

chore: add contributors to `README.md`

---

package.json

Babel dep was missed in package.json but present in package-lock.json

chore: add @babel/core as dev dep

---

tailwind.config.js

Because we are using a custom PostCSS config, tailwind was logging warnings during build:
>    ⚠️  Tailwind is not purging unused styles because no template paths have been provided.
>      If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
removing unused styles, set `purge: false` in your Tailwind config file to silence
this warning.
>   
>      https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
I've done exactly that.

chore: silence tailwind purge css error

---

src/lib/queryAdvise.js

Incorrect `id` attributes, can lead to a white-screen. One example of an invalid query that causing this is:
```html
<button 
id=
name="submit" 
/>
```
```js
container.querySelector('button')
```
[playground](https://testing-playground.com/#DwIwrgLhD2B2AEBLAJgXlgQwLYFNUCIBnMELRCfeAegD4g&MYewdgLghglmCmAnAdARwK5IJ4GV4Bt5gIREAKAcgCN0ISwKBKIA)
Everyone understands that this isn't valid HTML, but... it happens when we are typing in the editor.

fix: escape invalid id's to prevent WSOD

---

src/lambda/oembed/oembed.js

No need to pass `format` if their's only one.
We can make it default to `json` whenever we would want to support `xml` format too

feat: make oembed requests default to json type

---

.well-known/dnt-policy.txt
package.json

We don't have user tracking, so this won't be a problem.
DNT policy will be available under https://testing-playground.com/.well-known/dnt-policy.txt
Copied this one btw: https://www.eff.org/dnt-policy

chore: add dnt-policy

---

src/lambda/server/server.js

Their validator doesn't process it correctly yet, but it doesn't hurt to merge this. That way I can use it to contact their support.

feat: add support for iframely

---

src/lambda/oembed/oembed.js

Add quotes around `width` & `height`

fix: restore quotes around oembed iframe attributes

---

src/components/Context.js
src/components/Embedded.js
src/components/Playground.js
src/components/Preview.js
src/components/PreviewHint.js
src/components/Query.js
src/components/Result.js
src/components/ResultSuggestion.js
src/lib/cssPath.js
src/lib/queryAdvise.js
src/parser.js
src/plugin.html
src/plugin.js

This one is quite awesome!
The query (javascript) is now evaluated in a sandbox! This means, that having `window.location.href = "https://evil.corp"` will no longer redirect the user to a different (potentially bad) domain.
This change also demotes the importance of the `preview` pane. It now only holds a presentation of the `markup`, it's no longer being used to run the queries against. Hence, `htmlRoot` has been removed from the app context.
Thereby, it's no longer required to render the `preview`. Which is especially useful when rendering in embed mode (no hiding-workarounds required).
---
fixes #21 
resolves #66
closes #67

feat: evaluate javascript query in a sandbox

---

src/embed.js

The `type` attribute for `script` elements is optional, and defaults to `text/javascript`.
This PR add's support for untyped script elements in embed templates.
The following two examples, are now treated equal:
```html
<template data-testing-playground>
<script type="text/html">
<button>one</button>
</script>
<script type="text/javascript">
screen.getByRole('button');
</script>
</template>
```
```html
<template data-testing-playground>
<script type="text/html">
<button>one</button>
</script>
<script>
screen.getByRole('button');
</script>
</template>
```

feat: support template > script elements without type attribute

---

src/components/Preview.js

I messed up while porting #88 to `develop`

fix: prevent WSOD in preview pane

---

src/components/Context.js

The initial result should be parsed **after** setting default values, not before.

fix: blank initial state

---

package-lock.json
package.json
src/components/Editor.js
src/index.html
src/parser.js
tests/setupTests.js

This branch builds upon #96. `@testing-library/dom` is now imported from `npm` instead of included from `unpkg.com`

chore: import `@testing-library/dom` from npm instead of unpkg

---

package-lock.json
package.json
src/hooks/usePlayground.js
src/lib/logger.js

I've added a redux-logger inspired logger to our state reducer. This can be of immense help during development and enables us to detect problems early on.
The logger only outputs in development mode, or if you've set `debug` in `localStorage` (to enable logging in netlify preview environments.

chore: add state logger to improve developer experience

---

src/index.html
src/index.js

I was quite sure I've removed this one before, not sure why it's there again:
```html
<script	
type="text/javascript"	
src="https://www.unpkg.com/@testing-library/dom@7.5.6/dist/@testing-library/dom.umd.min.js"	
></script>
```
Also, instead of importing `service-worker.js` to initialize the service-worker in a separate bundle, I've combined it with the main bundle.

chore: remove unpkg import & move service-worker import

---

src/lib/getExpression.js

Clicking html elements with the mouse, already resulted in regex based matches, the blue buttons should do this as well.

fix: use regex based TextMatchers

---

src/components/Editor.js
src/components/MarkupEditor.js
src/components/Preview.js

Working on #10 , I have enabled:
1. html mixed mode in `MarkupEditor`, syntax highlighting working even for js script now
2. script tag are now retrieved in `Preview` component and evaluated through `window.eval`. Before `markup` is passed as `Scrollable` child in `dangerouslySetInnerHtml` all the `script` elements are removed.
Right now, this kind of code:
```html
<label for="checkbox">Check</label>
<input
id="checkbox"
type="checkbox"
/>
<button id="btn">
Accept
</button>
<button id="btn2">
Decline
</button>
<script>
const btn = document.getElementById('btn');
btn.addEventListener('click', () => {
alert('click');
});
</script>
<script>
const btn2 = document.getElementById('btn2');
btn2.addEventListener('click', () => {
alert('click no');
});
</script>
```
can be inserted by the user and …

feat: add support for mixed html/js content

---

README.md

Update the sentence:
> Create a template element, in which you add to script tags. One for html and one for javascript. Make sure to type them correctly, as that's the what that our embedder uses to populate the different panes.
To be:
> Create a template element, in which you add to script tags. One for html and one for javascript. Make sure to type them correctly, **as that's what our embedder uses to populate the different panes.**

fix typo in readME

---

src/components/Editor.js

**What**:
#128 changed the behavior of attribute indentations in the markup editor. This PR restores the old behavior.
**Why**:
Because it looks better. Compare:
```html
<div 
class="container">
</div>
<textarea
class="input">
</textarea>
```
with:
```html
<div
class="container">
</div>
<textarea
class="input">
</textarea>
```
**How**:
Pass the `multilineTagIndentPastTag: false` option to `CodeMirror`
**Checklist**:

fix: restore auto indent size in markup editor

---

src/parser.js

**What**:
Bugfix related to #161 
The Guard was modified now the Error is thrown if rootNode isn't in scope and markup is not a `typeof` "string"
**Why**:
The parser was triggering true when all the HTML was removed from the codemirror by the user.
**Checklist**:
**Screenshot before the fix applied on live site (in original bug report)**
**Screenshot locally running with fix applied and the HTML manually removed** 
**Tests ran after the fix is applied.**

fix: parser error on empty markup string, causing WSOD

---

.eslintrc.js
package-lock.json
package.json

**What**:
Add eslint plugin for `react-hooks`
**Why**:
To ensure best practices in declaring hook dependencies.
**How**:
Install `eslint-plugin-react-hooks`, and add the `react-hooks:recommended` plugin to the eslint config.
**Checklist**:

chore: add eslint config for react hooks

---

src/components/DomEvents.js
src/components/Preview.js
src/components/StickyList.js

**What**:
I've changed the node to which `DomEvents` listens for events. The node was positioned inside `DomEvents`, now we're listening to the `Preview` root instead.
**Why**:
Listening to a node that wraps the entire preview pane, causes unrelated events to be logged. This is because the `Preview` component doesn't only hold the raw markup, it also contains `Scrollable` and `AutoSizer` (resize detectors).
The `AutoSizer` triggers on page load, so it caused the first events to be directly added on-page load. This change fixes that as well.
**How**:
Use the callback ref to bind the events directly on the correct root node, instead of wrapping the entire `<Preview>` component.
**Checklist**:

fix: move target node for event logger a few nodes down

---

src/components/Editor.js
src/lib/beautify.js
src/lib/state.js

fix #196 
**What**:
On blur both the editor for js and html are now formatted
**Why**:
Because formatted text are more beautiful 💅 
**How**:
Adding an event handler for onBlur 
**Checklist**:

feat: format editor content on blur

---

src/components/Editor.js
src/lib/beautify.js
src/lib/state.js

**What**:
Added `on paste` formatting on top of #197 
**Why**:
Because if users paste their content, they might not realize that it will be formatted on blur. Formatting directly on paste, might prevent some manual formatting actions.
**How**:
Added an `on change` handler to CodeMirror, which ignores every change type except for the `paste` origin.
**Checklist**:

feat: format editor content on paste

---

src/components/Playground.js
src/components/Result.js

**What**:
Adding better scrolling for smaller screens like 11" Macbook.
[Original issue](https://github.com/testing-library/testing-playground/issues/149)
**Why**:
For better usability with people who have smaller screens.
**How**:
I got rid of the height on the main div around the `Result` Component and added `overflow-auto` and created a height on the inner component to trigger the scrollbar when it exceeds the height.
**Checklist**:
This is not ready to be merged, I am raising this in Draft mode to start a discussion on how to finish.
@smeijer There are two problems I have ran into:
1. I noticed the project uses tailwind but when I try and use `overflow-auto` is does not work, even though that is a valid style?
2. I cannot find where the query styles are coming from and in order to …

feat: add result suggestion to scrollable area for small screen support

---

src/components/Expandable.js
src/components/PreviewHint.js
src/lib/queryAdvise.js
src/styles/app.pcss

**What**:
When clicking on a wrapper element (e.g. div), it takes a screenshot of the inner elements.
**Why**:
The idea is to use less the toMatchSnapshot function. In this way, the tests will be more explicit. Something I noticed is that people tend to ignore the snapshots and just update them without thinking about it. This can be an elegant solution to avoid it. 
**How**:
Run getSuggestedQuery to every child of the external wrapper.
**Checklist**:

feat: add "snapshot" function for wrapper elements

---

src/components/ResultQueries.js

**What**:
After merging #150, the `develop` branch rendered completely blank on the initial load.
**Why**:
We can't work on a white screen
**How**:
Add conditional operators to `possibleQueries`, to prevent `can't read from undefined` errors.
**Checklist**:

fix: bug causing WSOD on initial render

---

scripts/build-client.js

**What**:
hopefully fixes https://github.com/testing-library/testing-playground/pull/143#issuecomment-648055517
**How**:
rewriting relative paths in meta tags to absolute

fix: correct `og:image` path in client build

---

scripts/build-client.js
src/components/Embedded.js
src/components/Expandable.js
src/lib/postMessage.js
src/sandbox.js

**What**:
The recent changes to the sandboxing had broken the embed mode. This has been fixed
**Why**:
Embed mode was broken
**How**:
- Communication through postMessage should target the parent frame, not just `top`.
- The sandbox (iframe) is now always being rendered
**Checklist**:

fix: apply sandboxing changes to embed mode

---

README.md

**What**:
I have replace the emoji key link in readme.
Before it addressed to https://github.com/all-contributors/all-contributors#emoji-key, now to https://allcontributors.org/docs/en/emoji-key that I think is the right link to be addressed to.
**Why**:
**How**:
**Checklist**:

fix emoji link in readme

---

devtools/src/content-script/highlighter/index.js
devtools/src/devtools/components/MenuBar.js

fix #228 
**What**: I have fixed an issue where the user can't disable inspecting after click on the icon
**Why**: User can't use the browser without a refresh
**How**: By saving state in a ref and toggle inspecting checking this 
**Checklist**:

fix(extension): toggle inspecting on button click

---

src/components/Editor.js

**What**:
fix editor mode detection for automated formatting
**Why**:
this fix exists on `live` but wasn't backported to `develop` yet
**How**:
For some reason, `options.mode` is sometimes a string like `html`, and sometimes an object like `{ name: 'html' }`. Fix is a simple one-liner:
```
const mode = cm.options.mode.name || cm.options.mode;
```
**Checklist**:

fix: incorrect detection of editor mode

---

src/components/Editor.js
src/components/ResultQueries.js
src/parser.js

**What**:
Fix suggestion buttons in chrome extension.
**Why**:
The suggestions are transported by `postMessage` from the page to the extension pane. This causes the data to be serialized and unserialized. But, `JSON.stringify({ foo: /regexp/i })` doesn't work!
**How**:
I've done two things here.
1. create a `toString` method that parses the query suggestion back to a full string. This fixes a `screen.[object Object]` bug, as we remove the `toString` method before handing it over to `postMessage`.
2. add a `toJSON` method and a `reviver` to serialize/deserialize RegExp's. This fixes a second bug, where queries like `screen.getByRole('button', { name: {} })` were generated.
**Checklist**:

fix(devtools): (de)serialize query suggestions for msg transport

---

src/components/Embed.js

**What**:
Forgot to push the last commit before merging #240 
**Why**:
Mistakes happen?
**How**:
Trying to do too much at once
**Checklist**:

fix: overflow issue in embed modal

---

postcss.config.js

**What**:
Add `data-reach` to the `whitelist` of `purgecss`
**Why**:
To fix the problem reported here: https://github.com/testing-library/testing-playground/pull/240#issuecomment-653893811
**How**:
Update `postcsss.config.js`
**Checklist**:

fix: add reach css selectors to purgecss whitelist

---

src/components/Layout.js
src/components/Preview.js
src/components/QueryEditor.js

**What**:
Fix #238 
**Why**:
To improve how the site looks and behaves in Safari to make it align with Chrome. 
**How**:
Update css classes to work on Safari. I'm not the best at css, but I removed/added some classes to make Safari show more like Chrome. I checked Chrome while making these changes as well and it didn't seem to be affected. Happy to look at a different/better way of doing things, or if there was something I missed 
**Safari**
**Chrome**
**Checklist**:

fix: fix css flex/height issues in safari

---

src/lib/queryAdvise.js

**What**:
Role field are set in `ResultQueries` even when they are related to an `input` element regardless of the `type` attribute.
**Why**:
In order to provide a more consistent information, because before the `role` query was rightly suggested but not shown in `ResultQueries`.
**How**:
**Checklist**:

retrieve role even for input element with type not text (#246)

---

devtools/src/content-script/highlighter/index.js
src/lib/queryAdvise.js

…on element (#237)
**What**:
Clicking on an `option` element into a `select` makes the `getByRole` query to be properly suggested.
This works only when `auto-run code` mode is disabled. I think this happens because when the code is automatically executed, clicking on a `select` input to open it, makes the `Preview` pane rerenders so the click on the `option` is missed.
**Why**:
In order to provide to the user a better experience.
**How**:
Before these changes it wasn't possible to obtain the right query clicking on an `option` element because no mouse or pointer event is related to this kind of element.
So I added an event listener on the `onChange` event on the `select` element.
**Checklist**:
-[x] add an `onChange` listener that in case of this event is performed on a `select` element …

feat: add support for query suggestions on select options

---

devtools/src/devtools/lib/inspectedWindow.js

**What**:
Escape queries before logging them to `inspectedWindow`
**Why**:
If we don't escape them, they won't be logged.
**How**:
Add slashes before single quotes and newlines.
**Checklist**:

fix(devtools): escape newlines in logged queries

---

devtools/src/content-script/contentScript.js
devtools/src/devtools/pane.js
devtools/src/devtools/panel.js
src/components/Expandable.js
src/components/Preview.js
src/components/PreviewHint.js
src/components/Result.js
src/components/ResultQueries.js
src/components/ResultSuggestion.js
src/lib/queryAdvise.js
src/lib/queryAdvise.test.js
src/parser.js
src/sandbox.js

**What**:
Add support for scoped queries.
Imagine having a checkout form with a `shipping address` and a `billing address`. Something like:
[playground](https://testing-playground.com/gist/d6ab40264c96af0c9a63f76f94caf010/84b3e61bcebde1e6a583f8602d87a8adeb10bdd0)
```html
<div>
<form aria-labelledby="shipping-addr">
<h1 id="shipping-addr">shipping</h1>
<label for="input1">address</label>
<input id="input1" name="address" placeholder="address" autocomplete="off" />
</form>
<form aria-labelledby="billing-addr">
<h1 id="billing-addr">billing</h1>
<label for="input2">address</label>
<input id="input2" name="address" placeholder="address" autocomplete="off" />
</form>
</div>
```
If we would select the "address input", playground will currently come up with a query like:
```js …
```

feat: add support for scoped queries

---

src/hooks/usePlayground.js
src/parser.js
src/sandbox.js

**What**:
It's a long story, that is partially explained in https://github.com/testing-library/testing-playground/issues/255#issuecomment-665515025, but long story short, we have multiple sources where we evaluate the query against the markup.
This pull-request changes that. The in-memory frame still feels like the best theoretical solution to me, but evaluating in the visible iframe, is the more practical solution.
I've removed the `runInSandbox` method from the parser. We now always use `runUnsafe` (in the DOM, against a visual element).
**Why**:
Because the query results in an in-memory iframe differ from the results in a visible iframe.
**How**:
**Checklist**:
---
fixes #255

refactor: only parse queries in sandbox

---

src/sandbox.js

**What**:
Prevent `<a href="` elements from opening links when being clicked.
**Why**:
It's frustrating that a click on `a` elements open a page when all we want is to have that selector.
**How**:
Prevent the click action, unless either `ctrl` or `shift` is being pressed as well. `ctrl+click` usually opens in a new tab, and `shift+click` opens in a new window. Both are explicit user actions, and thereby fine.
**Checklist**:

feat: prevent opening links, unless ctrl or shift clicked

---

devtools/src/devtools/panel.js
src/components/MarkupEditor.js
src/components/Preview.js
src/components/QueryEditor.js
src/hooks/usePlayground.js
src/sandbox.js

**What**:
This fixes the issue where selecting an `input` in the `sandbox`, causes a direct update of that same sandbox. The problem with that is that whatever is being typed in an `input`, is directly being undone.
**Why**:
Because not being able to type in inputs, is highly frustrating.
**How**:
Let the `state reducer` know that it's the `sandbox` that caused the update, so that it can skip the `sandbox update` effect.
Sandbox only updates the query, in a way that results to the same element selection. So we can skip a round trip, and highlight the element directly from within the sandbox.
**Checklist**:

fix: prevent sandbox update when clicking elements in sandbox

---

src/components/Header.js

**What**:
hide the `Testing Playground` title on small screens
**Why**:
Because the title is long, and pushes the `⋮` menu off screen.
**How**:
Tailwind `className="hidden sm:block"` :sunglasses: 
**Checklist**:

feat: hide app name on small screens

---

src/sandbox.js

**What**:
Update the suggestion pane when clicking elements in the preview pane.
**Why**:
PR #264 changed some things to prevent sandbox updates while selecting inputs so users can type in them. But at the same time, it broke direct updates of the suggestion pane.
**How**:
The `ON_SELECT_NODE` event now also triggers a `SANDBOX_READY`, which includes the parser result.
As the sandbox doesn't really evaluate anything, a `SANDBOX_BUSY` is not emitted.
**Checklist**:
---
fixes: #268

fix: update suggestion pane when clicking in preview pane

---

src/lambda/gist/gist.js

**What**:
Support saving markup-only playgrounds (without query).
**Why**:
Sometimes people don't know what query to use. To get feedback on based on their markup alone, it would be nice to be able to save a playground without queries. This also allows for easy third party integrations.
**How**:
Before posting the data to github, we now set the query to `// your query` and the markup to `` if they aren't provided. I've tried just submitting some whitespace or newlines. But GitHub ain't easy to fool.
**Checklist**:

feat: support saving with partial content

---

src/components/Header.js
src/components/Share.js
src/hooks/usePlayground.js

**What**:
Instead of showing a message: `this share url doesn't reflect the current state!!111`, we now make sure that it does.
**Why**:
Till now, we were warning the user when they try get a share link for an unsaved playground. Why not just save it for them though? In 99% of all cases, users want to share the current state.
**How**:
When the share modal opens, it's checking for a `dirty state`. When that's the case, it will render a spinner, and trigger the save action. Once the playground has been saved, it will render the share url.
**Checklist**:

feat: auto save on share

---

src/lambda/oembed/oembed.js

Just like you have at
https://github.com/testing-library/testing-playground/blob/dc14e4ae6430876cdb0a36fda09486fdb3ae6d93/src/components/Embed.js#L37

fix(oEmbed): Bring iframe in line with the embed in the GUI

---

src/components/Embed.js
src/components/Embedded.js
src/components/Header.js
src/components/Share.js
src/lambda/oembed/oembed.js
src/lambda/server/server.js

**What**:
Improve the user experience for embedding.
- Default frame height has been increased from 300px to 450px;
- Embed modal now saves state prior to showing embed code, instead of showing the "unsaved changes warning"
**Why**:
Nicer like this.
**How**:
**Checklist**:

feat: improve embed experience

---

src/sandbox.js

**What**:
Restore the `accessible roles` hint when the pointer leaves the sandbox frame.
**Why**:
Because this was clearly a bug.
**How**:
We now keep track of the fact if the pointer is inside or outside of the frame. As the `selectNode` can be triggered after `onMouseLeave`. To guard against this race condition, `onMouseEnter` and `onMouseLeave` maintain a `pointerInside` boolean, which is checked by `selectNode`.
**Checklist**:

fix: restore sandbox hint on mouse leave

---

devtools/src/devtools/lib/settings.js
src/components/Settings.js
src/hooks/usePlayground.js
src/lib/logger.js

fix #284
**What**:
Fix an issue when the user has disabled the use of cookies 
**Why**:
It was an issue
**How**:
Before using localStorage I have check that cookies are enabled. 
If cookies are disabled user settings will be reset on page refresh.
I have also added a warning on the settings
**Checklist**:

fix: don't use localStorage when browser blocks access

---

src/components/Embedded.js

The embedded version renders all panes next to each other in a row. Four panes, is really to much. So I defaulted it to `query` and `preview`.
It can still be configured by providing the `panes=markup,query,result,preview` query param.

feat: change default panes for embed mode to query,preview

---

src/lambda/oembed/oembed.js
src/lambda/server/server.js

We now validate the oembed url, and we correct it if the consumer provides a wrong playground url.
To get the oembed url, the consumer should retrieve it from the HTML. But it turns out not every consumer does this. Some figure out where we host the `oembed` api, and call that directly. Resulting in incorrect embed urls.
We can't do everything to support those consumers, but we now do replace the `/gist/` path with a `/embed/` to be a bit less strict.

feat: add url validation to oembed

---

package.json
src/lambda/oembed/oembed.js

Remove `const URL = require('url');` line, because `url.parse` is [deprecated](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) and `URL` is globally available [since Node 10](https://nodejs.org/api/globals.html#globals_url).
I also added the `engines` key to the `package.json` to make it clear that this project needs to be run on Node 10 as [`memoize-one`](https://github.com/alexreardon/memoize-one) needs it
https://github.com/alexreardon/memoize-one/blob/c7994d25b614531c7ccfd30cc34d49385e3fa678/package.json#L90

chore: use global URL instead of import

---

src/components/Embed.js
src/components/Embedded.js
src/constants.js
src/lambda/oembed/oembed.js

I think we should make the default panes of the embed consistent with the default panes from the embed modal

fix: bring embed panes in line with the embed in the GUI

---

src/components/Editor.js

**What**:
This PR fixes #297 keeping the `Editor` cursor cursor in the right position after paste event.
**Why**:
To fix #297 
**How**:
Calculating the last position based on the text pasted and moving the cursor there.
**Checklist**:

fix: persist cursor position on paste

---

src/components/Preview.js

**What**:
This PR fixes #243 
**Why**:
The way the browser work is how it's behaving, but it's a bit annoying to have popovers hanging around when clicking on the preview. Specially because the end user doesn't know that's an iframe.
**How**:
Attaching a listener to the `iframe` and propagating a `mousedown` on the body of the current window.
**Checklist**:

fix: close menu popovers when clicking inside preview pane

---

CONTRIBUTING.md
docs/features.md

**What**:
This PR resolves #223 making it clear for the contributor on how to proceed creating a new feature ad also what to use in case the need it.
**Checklist**:

docs: add developer docs

---

.gitignore
package-lock.json
package.json

**What**:
This PR fixes #305 
**Why**:
dom-testing-library added a `level` option to `byRole` methods to help distinguish between headings of different levels. Because testing-playground was using an outdated version of dom-testing-library, this query functionality wasn't available.
**How**:
Updated `package.json` by running `npm update @testing-library/dom`. The `byRole` queries with the `level` option now work as expected.
**Checklist**:
I also added a line to `.gitignore` to prevent committing configuration files automatically created by Webstorm.

chore(deps): update @testing-library/dom to 7.28.1

---

src/components/App.js
src/components/DomEvents.js
src/components/Embed.js
src/components/Loader.js
src/components/Playground.js
src/components/PlaygroundPanels.js
src/components/TabButton.js
src/context/PreviewEvents.js
src/lib/domEvents.js

**What**:
This PR fixes #172 and merge the `/events` route with the playground, showing the two views together and making it possible for the user to switch between them.
**Why**:
Required from #172 in which we wanted a way to switch between views.
**How**:
* Extracted `TabButton` to be used from `Embed` and the new view.
* Created a new component called `PlaygroundPanels`
* Moved the bottom part of `DomEvents` view into `PlaygroundPanels`
* Moved the bottom part of `Playground` into `PlaygroundPanels`
* Refactor functionality of `DomEvents` into a context, so we are able to get the correct `ref` for the `Preview`
* Extracted `DomEvent` dom utilities into separate file.
**Checklist**:

feat: add tabs to switch between query and event mode

---

.eslintignore
.github/workflows/ci.yml
.gitignore
.prettierignore

**What**: run cypress on CI
**Why**: to be sure that e2e pass
**How**:
**Checklist**:

ci: run cypress

---

src/components/Playground.js
src/components/PlaygroundPanels.js

**What**:
`Playground` now passes `state` and `dispatch` to `PlaygroundPanels` and `PlaygroundPanels` does not call any more `usePlayground` hook to retrieve these two values.
**Why**:
This fixes #314 introduced by #296.
**How**:
**Checklist**:

fix: restore change detection in query pane

---

package-lock.json
package.json
scripts/build-devtools.js

**What**: Adding support for Firefox extensions
**Why**: So people who use Firefox can use this extension
**How**: Adding the [web-ext](https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/) package, we can run and build the extension in firefox
**Checklist**:
It is ready to run:
1. In project root, execute `build:devtools:firefox`
2. Then on firefox, go to `about:debugging#/runtime/this-firefox`
3. Click on **Load temporary add-on** 
4. Select the `.zip` file from `<project_root>/dist/` folder and click **open**
5. There is 2 warnings about the manifest.json, but testing it out, it works

feat: make extension build scripts firefox compatible

---

src/components/IconButton.js
tailwind.config.js

**What**:
This PR fixes https://github.com/testing-library/testing-playground/issues/343 by improving the color contrast between foreground and background colors used with several interactive UI elements. 
**Why**: 
Insufficient color contrast was causing the expand/collapse trigger element difficult to see for non-impaired and impaired users. This is an interactive element and its clickable target is small, so if a user cannot see the `<IconButton>`, they cannot expand/collapse certain elements.
**How**:
The default color used for `gray-500` was overridden with a darker shade via extending the `tailwind.config.js`. In addition, the `<IconButton>` component was updated to make its `light` and `dark` variants use the new color.
**Checklist**:
Below artifacts show examples of the fix and …

fix: improve icon button color contrast

---

src/sandbox.js

**What**:
As mentioned in this [issue](https://github.com/testing-library/testing-playground/issues/338), when we have a list, the tool does not show us other possible query options.
Example:
**Why**:
To improve the developer experience, the following function was added, basically we check if there is any valid query, if there is none, it works with the previous implementation.
```js
function checkQuery(queries) {
const suggestions = Object.values(queries).filter(Boolean);
const suggestion = Object.values(queries).find(Boolean);
const anotherSuggestion = suggestions.find(
(query) =>
query?.queryName && !query.snippet?.startsWith('// sorry, I failed'),
);
return anotherSuggestion ? anotherSuggestion : suggestion;
}
```
Print screen:
As it maintains the order of the elements, the best query …

fix: sandbox not render another queries

---

src/components/Header.js

**What**:
Removing the link to the Firefox extension from the page
**Why**:
The link is broken and the extension doesn't seem to exist under a new link either as far as I can see from the Firefox extension site and #344.
**How**:
Removing the link from the top bar
**Checklist**:
Thanks in advance for the help! :)

Remove broken link to Firefox extension

---

src/components/Header.js

the linked roadmap is now closed

remove link to a closed roadmap

---

vite.config.ts

**What**:
`/embed.js` file is missing from the built output.
**Why**:
While the embed.js file is missing it is not possible to load the embed.js file:
```
<script async src="https://testing-playground.com/embed.js"></script>
```
**How**:
Added embed.js to the built output.
**Checklist**:

Add missing embed.js file to built output
