- .github/workflows/lint.yml
- package.json
Creating a PR, to test the actions.
> chore: use github-actions to lint pull-requests

- postcss.config.js
I fixed the problem with Tailwind. This fix solve the problem of responsive for fix #16 🎉
> chore: fix extractor for Tailwind

- src/components/App.js
- src/styles/app.pcss
> feat: make layout responsive to improve UX on small screens

- src/lambda/oembed/oembed.js
> chore: fix code style in oembed.js

- src/lambda/server/server.js
> chore: fix code style in server.js

- src/components/Embedded.js
- src/components/Playground.js
- src/hooks/usePlayground.js
I created an hook that will handle all the thing required to run the playground.
> chore: move state handling to usePlayground hook

- CONTRIBUTING.md
- README.md
I have fixed the link in the README.md and changed the branch to develop
> docs: update contributing.md

- src/components/Preview.js
fixes #87, the provided [REPL][repl] crashed when hovering some of the buttons.
This was caused by a `text` node, not having the `querySelector` methods.
[repl]: https://testing-playground.com/?markup=AQHgRg9gJgnsDGAbAhgZ1QXgESIJYHMALAFwFoBbaAUywD4AoEKXAN3qTUywBUI1iqAJyz1cUbIKrJ4ZYn1TERDEKgAOyAHbsU6bL35CA%2BofKbk%2BIaTmqRCmIirZTAD1IB3McUIAuYAFYANgAGVWcAbmBVCFRcYlwIDV8AM1xnKigIgC9SXA0oKmdfPz8goIio3IFBUioWKg1iVF8NBKoI00F8XN8Q52BkAFc5CIFnMmQ8fESEeqqRiFUe0IjBAhIl8OAHJOINsJEAemU1TW1OPXkq41MNc0trUm3FejsHJ2RXDygvIuDlyOisXi0xSaQywGyuXyhX8JTKAMqllqsyawBaGjawGsey2VB2e0Ox3UWg4uh4lyMJjMFmqD1WRGer0cWBc7k8Pn8f02URicQSyVS6SyOTyBSKcPKEER1WRDVR6Mx2OAvRWa12yuWhMYJxJOi4%2BgUlJud2qkGIcnIjzxjOI9mZrK%2BP05KoBvOBArBwqhYthpUl0pqdTlzVaETNFpxTwJ9CO2uJZzJBquVNuNNI4Yg5FstreLI%2BbO%2BHMCLp5QP5wFBQohIuh4r9CIaSKDjRDGPay …
> fix: bug causing white screen when mouse moves in preview pane

- package-lock.json
- package.json
- src/lib/queryAdvise.js
- src/lib/queryAdvise.test.js
- tests/setupTests.js
> feat: use `getSuggestedQuery` from `@testing-library/dom`

- src/hooks/usePlayground.js
> fix: bug setting query to wrong prop in state

- scripts/build.js
**What**:
I've enabled react refresh (hot-module-reloading) when running in the playground in dev mode.
**Why**:
To improve developer experience.
**How**:
Import parcel default config in the build script. And especially, assign an available port to the `hot.port` option.
**Checklist**:
> chore: enable hmr (react-refresh) on dev env

- .github/ISSUE_TEMPLATE/1.bug.md
- .github/ISSUE_TEMPLATE/2.feature.md
- .github/ISSUE_TEMPLATE/Bug_Report.md
- .github/ISSUE_TEMPLATE/config.yml
Fix #125 
**What**:
I have added template for every issues
**Why**:
We need them to mantain the project better
**How**:
Adding some .md files in .github folder
**Checklist**:
> chore: add issue templates

- src/lib/logger.js
**What**:
Change the default visibility setting of the logger to:
- enabled, in case it's running in `development` mode AND it's not disabled explicitly.
- disabled, in case it's running in `production` mode UNLESS it's enabled explicitly.
**Why**:
Because it wasn't configured right, and was frustrating me.
**How**:
```
const isLoggingEnabled =
process.env.NODE_ENV === 'development'
? localStorage.getItem('debug') !== false
: localStorage.getItem('debug') === true;
```
**Checklist**:
> chore: change logger settings

- src/components/DomEvents.js
**What**:
Clean up all events attached to preview
**Why**:
Because it can be a problem if in the feature we could jump from events and editor 
**How**:
I have replaced `useCallback` with `useEffect`. On return function of the `useEffect` I have removed events
**Checklist**:
> fix: add cleaning of events attached to dom-events preview node

- .babelrc
- .eslintrc.js
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .lintstagedrc.js
- CODE_OF_CONDUCT.md
- MAINTAINING.md
- README.md
- devtools/src/devtools/main.html
- devtools/src/devtools/pane.html
- devtools/src/devtools/panel.html
- devtools/src/manifest.json
- src/components/Editor.js
- src/embed.html
- src/styles/app.pcss
- src/styles/codemirror.pcss
**What**:
Add rule to eslint config for curly braces
**Why**:
So that we don't need to think about it ourselves. Write how you want it, and the commit hook will reformat.
commit:
```js
if (!true) return;
```
push:
```js
if (!true) {
return;
}
```
**How**:
Update `.eslintrc.js` and run `npm run lint`
**Checklist**:
> chore: add rule for eslint curly braces && lint them all

- src/styles/app.pcss
**What**:
Added more styles to the preview pane to style default HTML elements.
**Why**:
To look pretty :lipstick: :relaxed:
**How**:
Added a couple of styles to `app.pcss`
**Checklist**:
before/after
> feat: improve styles in preview pane

- .github/workflows/ci.yml
**What**:
I've added an action that assigns pull requests to their authors.
**Why**:
Because now I'm doing it manually. Better automate it.
**How**:
Added an action to the github workflow.
**Checklist**:
> chore: add action to auto assign pull-requests

- .github/ISSUE_TEMPLATE/1.bug.md
- .github/ISSUE_TEMPLATE/2.feature.md
**What**:
I've added "default labels" to `bug` and `feature` issue templates.
**Why**:
So that new bug reports automatically get assigned a `bug` label, and new feature request a `feature` label.
**How**:
Updated the issue templates.
**Checklist**:
> chore: add default labels to issue templates

- postcss.config.js
**What**:
Fix the hot reloading of tailwind css during development.
**Why**:
Currently, it's not possible to apply unused tailwind classes, without a full restart of node. This is quite frustrating.
**How**:
Fix the `IS_DEVELOPMENT` check in `postcss.config.js`.
**Checklist**:
fixes #183
> chore: fix tailwind hot reload

- .eslintrc.js
- src/components/ResultQueries.js
- tests/setupTests.js
**What**:
I've updated the `eslint` config to include a rule for `body style`.
**Why**:
To maintain a uniform code style without the developer needing to think about it.
**How**:
Add `arrow-body-style: ['error', 'as-needed']` to `.eslintrc.js`
**Checklist**:
Replaces #201, turns out, `as-needed` results in the preferred style
> chore: add eslint arrow-body-style config

- package-lock.json
- package.json
**What**:
Upgrade `@testing-library/user-event` and `@testing-library/dom` to the latest versions.
**Why**:
To include https://github.com/testing-library/dom-testing-library/commit/373dbc400689f4c9c987192b6ecf85b0f7de2e31, which fixes #214 
**How**:
```
npm i @testing-library/dom @testing-library/user-event
```
**Checklist**:
> chore: update @testing-library/dom & @testing-library/user-event

- src/lambda/gist/gist.js
**What**:
Authenticate gist fetch requests as well
**Why**:
Authenticated requests have much higher rate limits
**How**:
Add authentication header.
**Checklist**:
> feat: authenticate fetch requests for higher rate limits

- src/components/Embed.js
- src/components/Embedded.js
- src/components/Header.js
- src/components/Layout.js
- src/components/Loader.js
- src/components/Modal.js
- src/components/Playground.js
- src/styles/app.pcss
**What**:
**Why**:
Because now the user has a way to generate their embed urls.
**How**:
Time, and a coffee or 2.
**Checklist**:
---
fixes #54
> feat: add embed modal

- src/components/Header.js
**What**:
Add a link to the [Chrome Extension](https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano) to the ⋮ menu
**Why**:
See #222
**How**:
-
**Checklist**:
resolves #222
> feat: add link to chrome extension

- devtools/src/window/testing-library.js
**What**:
Adjust the chrome-extension injected script to also add `user-event` to the `window` object.
**Why**:
So users can play with userEvent on their console.
**How**:
see "changed files"
**Checklist**:
> feat(devtools): add user-event to window object

- src/styles/app.pcss
**What**:
Style the sandbox `headings`
**Why**:
To distinguish them from bold text
**How**:
Add `.preview h{1-6}` styles
**Checklist**:
> feat: improve style in preview pane

- devtools/src/window/testing-library.js
**What**:
add `getRoles` to `window`
**Why**:
Because it's useful to be able to inspect all roles present on a page (`getRoles(document.body)`)
**How**:
seriously? :confused: 
**Checklist**:
> feat(devtools): add getRoles to window

- src/sandbox.js
**What**:
Ooops, I killed the persistent highlight in #260. I should add tests :disappointed: 
**Why**:
**How**:
**Checklist**:
> fix: highlight of selected elements

- src/sandbox.js
**What**:
Fixes https://github.com/testing-library/testing-playground/pull/261#issuecomment-665642604
> fix: highlight selector when no results

- src/hooks/usePlayground.js
- src/lib/state/url.js
**What**:
Fix restore for state-full urls.
**Why**:
We've migrated to gist id's a while back, but storing state in urls, allows for easy third-party integrations.
**How**:
Easy-peasy. 
**Checklist**:
> fix: restore support for state-full urls

- .github/workflows/cd.yml
- .github/workflows/ci.yml
**What**:
Use a different github token, and remove the `meta` action that assigns the PR author as `assignee`
**Why**:
Assigning the PR author as assignee is nice. But it only works for registered contributors. So for every external author, the action will fail, and thereby it looks like the CI fails. Which sucks.
**How**:
SELECT -> DELETE -> COMMIT. :sleepy: 
**Checklist**:
> chore: update github actions

- src/components/Header.js
**What**:
rename `issue tracker` in the menu to `GitHub`
**Why**:
It's better that way.
**How**:
I've hired a 10x engineer.
**Checklist**:
> chore: rename issue tracker link to GitHub

- src/embed.html
Add update button to `embed.html` demo page
> chore: add update button to embed demo

- src/lambda/oembed/oembed.js
- src/lambda/server/server.js
**What**:
Correct oembed frame source
**Why**:
#283 didn't work
**How**:
**Checklist**:
> fix: correct oembed frame source

- package.json
- src/lambda/oembed/oembed.js
Revert #291 , as it breaks build.
> revert: use global URL instead of import (#291)

- public/site.webmanifest
**What**:
This PR fixes #224 
**Why**:
We want to support any orientation on PWA
**How**:
* Modifiying PWA webmanifest orientation to `any`
**Checklist**:
> changed orientation on webmanifest

- package-lock.json
- package.json
**What**:
This PR fixes `MenuButton` popover, which i fixed directly on `react-ui/menu-button` https://github.com/reach/reach-ui/pull/700
**Before**
**After**
**How**:
Bumped up `@reach-ui/menu-button` to latest, also make sure we are not using any deprecated prop
**Checklist**:
> chore(deps): bump @reach/menu-button to 0.12.1

- package-lock.json
- package.json
**What**:
revert parcel to `2.0.0-nightly.280`
**Why**:
Parcel was updated as part of #310, but it broke build due to a conflicting postcss requirement
**How**:
```
npm i parcel@2.0.0-nightly.280
```
**Checklist**:
> chore(deps): revert parcel to 2.0.0-nightly.280
